// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "tds/shared/models"

	mock "github.com/stretchr/testify/mock"
)

// IDatasetService is an autogenerated mock type for the IDatasetService type
type IDatasetService struct {
	mock.Mock
}

// GetAllDatasets provides a mock function with given fields: ctx
func (_m *IDatasetService) GetAllDatasets(ctx context.Context) []*models.Dataset {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDatasets")
	}

	var r0 []*models.Dataset
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Dataset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Dataset)
		}
	}

	return r0
}

// IsLabelValid provides a mock function with given fields: label
func (_m *IDatasetService) IsLabelValid(label string) bool {
	ret := _m.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for IsLabelValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(label)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ReloadCache provides a mock function with given fields: ctx
func (_m *IDatasetService) ReloadCache(ctx context.Context) {
	_m.Called(ctx)
}

// Save provides a mock function with given fields: ctx, dataset
func (_m *IDatasetService) Save(ctx context.Context, dataset *models.Dataset) (*models.Dataset, error) {
	ret := _m.Called(ctx, dataset)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.Dataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Dataset) (*models.Dataset, error)); ok {
		return rf(ctx, dataset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Dataset) *models.Dataset); ok {
		r0 = rf(ctx, dataset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Dataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Dataset) error); ok {
		r1 = rf(ctx, dataset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDatasetService creates a new instance of IDatasetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDatasetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDatasetService {
	mock := &IDatasetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
