// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPublishService is an autogenerated mock type for the IPublishService type
type IPublishService struct {
	mock.Mock
}

// EnqueueExportJob provides a mock function with given fields: exporterId, reducer, dataset
func (_m *IPublishService) EnqueueExportJob(exporterId string, reducer string, dataset string) {
	_m.Called(exporterId, reducer, dataset)
}

// EnqueueTrainingJob provides a mock function with given fields: modelId, exporterId, reducer
func (_m *IPublishService) EnqueueTrainingJob(modelId string, exporterId string, reducer string) {
	_m.Called(modelId, exporterId, reducer)
}

// NewIPublishService creates a new instance of IPublishService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPublishService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPublishService {
	mock := &IPublishService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
