// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	models "github.com/Tracking-Detector/td_backend_infra/microservices/shared/models"
	mock "github.com/stretchr/testify/mock"
)

// ReduceFunction is an autogenerated mock type for the ReduceFunction type
type ReduceFunction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ReduceFunction) Execute(_a0 []models.RequestDataLabel) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func([]models.RequestDataLabel) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewReduceFunction creates a new instance of ReduceFunction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReduceFunction(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReduceFunction {
	mock := &ReduceFunction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
