// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IConsumer is an autogenerated mock type for the IConsumer type
type IConsumer struct {
	mock.Mock
}

// Consume provides a mock function with given fields:
func (_m *IConsumer) Consume() {
	_m.Called()
}

// NewIConsumer creates a new instance of IConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConsumer {
	mock := &IConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
