version: '3.3'

networks:
  app-network:
    driver: bridge
volumes:
  mongo_storage:
  authelia_data:
  minio_data:

services:
  # api gateway
  traefik:
    container_name: traefik
    image: traefik:v2.9
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=http'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=false'
      - 'traefik.http.routers.api.tls.options=default'
      - "traefik.http.middlewares.stripapi.stripprefix.prefixes=/api"
      # - 'traefik.http.routers.api.middlewares=authelia@docker'
      
    depends_on:
      - mongo-express
    command:
      - '--api'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--log=true'
      - '--log.level=DEBUG'
    networks:
      - app-network

  # infra
  db:
    image: mongo:4.4.18
    restart: unless-stopped
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=tracking-detector
    volumes:
      - mongo_storage:/data/db
    networks:
      - app-network

  minio:
    restart: unless-stopped
    image: minio/minio
    container_name: minio
    volumes:
      - minio_data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.minio.rule=Host(`minio.${DOMAIN}`)'
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      # - 'traefik.http.routers.minio.middlewares=authelia@docker'  
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_PRIVATE_KEY}
    command: server ~ --address ':9000' --console-address ':9001'
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - app-network


  # ui
  mongo-express:
    container_name: mongo-express
    restart: unless-stopped
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017/tracking-detector
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_SITE_BASEURL=/mongo
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mongo-express.rule=(Host(`app.${DOMAIN}`) && PathPrefix(`/mongo`))' 
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"
    depends_on:
      - db
    networks:
      - app-network
  monit:
    container_name: monit
    image: pottava/docker-webui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.monit.rule=Host(`docker.${DOMAIN}`)' 
      - "traefik.http.services.monit.loadbalancer.server.port=9000"
    environment:
      - DOCKER_HOST
    networks:
      - app-network

  # microservices
  requests:
    restart: unless-stopped
    container_name: requests
    build: 
      context: .
      dockerfile: ./microservices/functions/requests/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_COLLECTION=${USER_COLLECTION}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - TRAINING_RUNS_COLLECTION=${TRAINING_RUNS_COLLECTION}
      - MINIO_URI=${MINIO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_PRIVATE_KEY=${MINIO_PRIVATE_KEY}
      - EXPORT_BUCKET_NAME=${EXPORT_BUCKET_NAME}
      - MODEL_BUCKET_NAME=${MODEL_BUCKET_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      - minio
      - db
    labels:
      - microservice=requests
      - 'traefik.enable=true'
      - 'traefik.http.routers.requests.rule=(Host(`app.${DOMAIN}`) && PathPrefix(`/api/requests`))' 
      - 'traefik.http.routers.requests.middlewares=stripapi@docker'
      - "traefik.http.services.requests.loadbalancer.server.port=8081"
    networks:
      - app-network

  download:
    restart: unless-stopped
    container_name: download
    build:
      context: .
      dockerfile: ./microservices/functions/download/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_COLLECTION=${USER_COLLECTION}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - TRAINING_RUNS_COLLECTION=${TRAINING_RUNS_COLLECTION}
      - MINIO_URI=${MINIO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_PRIVATE_KEY=${MINIO_PRIVATE_KEY}
      - EXPORT_BUCKET_NAME=${EXPORT_BUCKET_NAME}
      - MODEL_BUCKET_NAME=${MODEL_BUCKET_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      - minio
      - db
    labels:
      - microservice=download
      - 'traefik.enable=true'
      - 'traefik.http.routers.download.rule=(Host(`app.${DOMAIN}`) && PathPrefix(`/api/transfer`))' 
      - 'traefik.http.routers.download.middlewares=stripapi@docker'
      - "traefik.http.services.download.loadbalancer.server.port=8081"
    networks:
      - app-network
  
  users:
    restart: unless-stopped
    container_name: users
    build:
      context: .
      dockerfile: ./microservices/functions/users/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_COLLECTION=${USER_COLLECTION}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - TRAINING_RUNS_COLLECTION=${TRAINING_RUNS_COLLECTION}
      - MINIO_URI=${MINIO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_PRIVATE_KEY=${MINIO_PRIVATE_KEY}
      - EXPORT_BUCKET_NAME=${EXPORT_BUCKET_NAME}
      - MODEL_BUCKET_NAME=${MODEL_BUCKET_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      - minio
      - db
    labels:
      - microservice=users
      - 'traefik.enable=true'
      - 'traefik.http.routers.users.rule=(Host(`app.${DOMAIN}`) && PathPrefix(`/api/users`))' 
      - 'traefik.http.routers.users.middlewares=stripapi@docker'
      - "traefik.http.services.users.loadbalancer.server.port=8081"
    networks:
      - app-network

  dispatch:
    restart: unless-stopped
    container_name: dispatch
    build:
      context: .
      dockerfile: ./microservices/functions/dispatcher/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_COLLECTION=${USER_COLLECTION}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - TRAINING_RUNS_COLLECTION=${TRAINING_RUNS_COLLECTION}
      - MINIO_URI=${MINIO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_PRIVATE_KEY=${MINIO_PRIVATE_KEY}
      - EXPORT_BUCKET_NAME=${EXPORT_BUCKET_NAME}
      - MODEL_BUCKET_NAME=${MODEL_BUCKET_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - MODELS_COLLECTION=${MODELS_COLLECTION}
    depends_on:
      - minio
      - db
      - rabbitmq
    labels:
      - microservice=dispatch
      - 'traefik.enable=true'
      - 'traefik.http.routers.dispatch.rule=(Host(`app.${DOMAIN}`) && PathPrefix(`/api/dispatch`))' 
      - "traefik.http.services.dispatch.loadbalancer.server.port=8081"
      - 'traefik.http.routers.dispatch.middlewares=stripapi@docker'
    networks:
      - app-network

  export:
    restart: unless-stopped
    container_name: export
    build:
      context: .
      dockerfile: ./microservices/functions/export/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_COLLECTION=${USER_COLLECTION}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - TRAINING_RUNS_COLLECTION=${TRAINING_RUNS_COLLECTION}
      - MINIO_URI=${MINIO_URI}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_PRIVATE_KEY=${MINIO_PRIVATE_KEY}
      - EXPORT_BUCKET_NAME=${EXPORT_BUCKET_NAME}
      - MODEL_BUCKET_NAME=${MODEL_BUCKET_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      - minio
      - db
      - rabbitmq
    labels:
      - microservice=export
    networks:
      - app-network