// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"w-full bg-gradient-to-r from-purple-500 via-pink-600 to-red-600 text-white px-4\"><div class=\"container mx-auto\"><div class=\"flex justify-between items-center\"><div class=\"text-center md:text-left\"><h3 class=\"text-lg font-semibold\">Tracker Detector</h3><p class=\"text-sm\">Protect your privacy with AI.</p></div><div class=\"mt-4 md:mt-0\"><ul class=\"flex space-x-4\"><li><a class=\"text-sm text-gray-300 hover:text-white\" href=\"#\">Features</a></li><li><a class=\"text-sm text-gray-300 hover:text-white\" href=\"#\">Products</a></li><li><a class=\"text-sm text-gray-300 hover:text-white\" href=\"#\">Installation</a></li><li><a class=\"text-sm text-gray-300 hover:text-white\" href=\"#\">Contact</a></li></ul></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
