// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"container mx-auto flex justify-between items-center px-4\"><a href=\"#\"><span class=\"font-bold text-2xl lg:text-4xl text-white\">Tracker Detector</span></a><nav><a class=\"text-white font-bold relative group mx-4\" href=\"#\">Features <span class=\"absolute left-0 right-0 bottom-0 top-3 h-[2px] bg-current rounded-full transform scale-x-0 group-hover:scale-x-100 transition-transform origin-center mt-3\"></span></a> <a class=\"text-white font-bold relative group mx-4\" href=\"#\">Products <span class=\"absolute left-0 right-0 bottom-0 top-3 h-[2px] bg-current rounded-full transform scale-x-0 group-hover:scale-x-100 transition-transform origin-center mt-3\"></span></a> <a class=\"text-white font-bold relative group mx-4\" href=\"#\">Installation <span class=\"absolute left-0 right-0 bottom-0 top-3 h-[2px] bg-current rounded-full transform scale-x-0 group-hover:scale-x-100 transition-transform origin-center mt-3\"></span></a> <a class=\"text-white font-bold relative group ml-4\" href=\"#\">Contact <span class=\"absolute left-0 right-0 bottom-0 top-3 h-[2px] bg-current rounded-full transform scale-x-0 group-hover:scale-x-100 transition-transform origin-center mt-3\"></span></a></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
