// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestHeadersExtractor is an autogenerated mock type for the RequestHeadersExtractor type
type RequestHeadersExtractor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RequestHeadersExtractor) Execute(_a0 []map[string]string) ([]int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func([]map[string]string) ([]int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]map[string]string) []int); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func([]map[string]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRequestHeadersExtractor creates a new instance of RequestHeadersExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestHeadersExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestHeadersExtractor {
	mock := &RequestHeadersExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
